### ISSUE TITLE
WindowsOSProcess.getUser() throws a Win32Exception

### ISSUE THREAD

**Issue by rnaval** [oshi/oshi#1551]
Error is:

`com.sun.jna.platform.win32.Win32Exception: The parameter is incorrect.
	at com.sun.jna.platform.win32.Advapi32Util.getAccountBySid(Advapi32Util.java:285)
	at com.sun.jna.platform.win32.Advapi32Util.getAccountBySid(Advapi32Util.java:251)
	at com.sun.jna.platform.win32.Advapi32Util.getTokenAccount(Advapi32Util.java:548)
	at oshi.software.os.windows.WindowsOSProcess.queryUserInfo(WindowsOSProcess.java:360)
	at oshi.util.Memoizer$1.get(Memoizer.java:87)
	at oshi.software.os.windows.WindowsOSProcess.getUser(WindowsOSProcess.java:148)`

Seems to be similar to https://github.com/oshi/oshi/issues/637, which was fixed by https://github.com/oshi/oshi/pull/641

We were able to reproduce it at using an AWS instance running Windows Server 2016 Datacenter. There seems to be no special steps to reproduce - just run and this will eventually come up.

**Comment by dbwiddis** [comment]
Indeed it is probably the same as #637, and catching the exception seems to have been lost in the 5.x refactor.  Which means the same fix should probably be applied.

**Comment by dbwiddis** [comment]
I've changed this from an exception to a log warning.  If you can try the SNAPSHOT release and try to reproduce it again, I'd be interested in the log warning (it will have the PID and process name).

**Comment by rnaval** [comment]
@dbwiddis Thanks for that. Here are some of the warning logs that we got upon using oshi 5.6.0:

`WARN  oshi.software.os.windows.WindowsOSProcess - Failed to query user info for process 4532 (cmd): 0`
`WARN  oshi.software.os.windows.WindowsOSProcess - Failed to query user info for process 3228 (sihost): 0`

**Comment by mfujitaitrs** [comment]
Hi @dbwiddis, to add to @rnaval's comment: 

- The machine in an EC2 instance using Windows Server 2016 AMI.

- This oshi log `WARN oshi.software.os.windows.WindowsOSProcess - Failed to query user info for process 3228 (sihost): 0`. Pertains to this process being ran by Administrator:
![image](https://user-images.githubusercontent.com/42991925/109788348-31cee980-7c4a-11eb-864d-6667abd3e4f1.png)

- Do note that the user running the application that uses Oshi library is also Administrator.

- It is also evident on a process owned SYSTEM.
`WARN  oshi.software.os.windows.WindowsOSProcess - Failed to query user info for process 3716 (ShellExperienceHost): 0`
![image](https://user-images.githubusercontent.com/42991925/109789574-7018d880-7c4b-11eb-8169-56be417ecaa1.png)

**Comment by dbwiddis** [comment]
Thank you for following up with the additional information!  Are these log warnings rare enough that they're acceptable noise or do you think they should be lowered to debug?  Do we know anything more about these processes and the timing of the warning? Did they just start up, for example?

Unfortunately, the "last error" of 0 indicates I made a small mistake with the log statement. The JNA exception already records that!  I'll have to update to get more info.  (If you can test again with the current 5.6.1-SNAPSHOT I'd appreciate it.)

Tracing through the code, the following sequence occurs in the problematic JNA call:
 - GetTokenInformation is called once with a null buffer/0 length to get the token information length (success)
 - GetTokenInformation is called a second time to populate a TOKEN_USER structure wrapping a SID_AND_ATTRIBUTES structure (success)
 - Using the pointer to the SID, calls LookupAccountSid with null buffers/0 length to get name and domain name length (success)
 - Allocates a `char[]` array for the size of those names
 - Calls LookupAccountSid again to populate the buffers. (Exception.)

So this suggests a possible race condition where either the domain (`EC2AMAZ-3H01JAF`) or name (`Administrator`) changes in length between those two calls.

**Comment by dbwiddis** [comment]
The domain name seems most likely to have something odd happening:

> `ReferencedDomainName`
> 
> A pointer to a buffer that receives a null-terminated string that contains the name of the domain where the account name was found.
> 
> On a server, the domain name returned for most accounts in the security database of the local computer is the name of the domain for which the server is a domain controller.
>
> On a workstation, the domain name returned for most accounts in the security database of the local computer is the name of the computer as of the last start of the system (backslashes are excluded). If the name of the computer changes, the old name continues to be returned as the domain name until the system is restarted.
>
> Some accounts are predefined by the system. The domain name returned for these accounts is BUILTIN.

**Comment by dbwiddis** [comment]
@rnaval we're looking to release a new version of JNA shortly and I'd like to get a fix for this in quickly.  Any chance you can re-test the latest SNAPSHOT and tell me the log warnings you get?

**Comment by dbwiddis** [comment]
So this is getting more interesting.  [This comment](https://github.com/hashbrowncipher/puppet-1/blob/master/spec/integration/util/windows/principal_spec.rb#L19) says:
> # Windows API LookupAccountSid behaves differently if current user is SYSTEM

A similar comment [here](https://tickets.puppetlabs.com/browse/PUP-5538?focusedCommentId=260940&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-260940):
> running under Jenkins as the SYSTEM user (which changes the behavior of LookupAccountSid)  ...

Apparently "NT Authority/SYSTEM" is not actually a user.   So far I can't find any documentation on what that different behavior is.

**Comment by dbwiddis** [comment]
Ah, [here is the difference](https://github.com/puppetlabs/puppet/commit/d376814db9c8110517272c778041a3ce7004332a):
> The behavior of the Windows API is inconsistent and LookupAccountSid
>   when executed as SYSTEM, returns an account type of SidTypeUser for
>   the SYSTEM account. When the same API is called by another user, it
>  returns SidTypeWellKnownGroup for the SYSTEM account.

Although that doesn't seem relevant to this case, so we're back to needing to reproduce again with the debugging log warnings.

**Comment by dbwiddis** [comment]
After a lot of reading, my current suspicion is that the domain name is empty.  The code currently checks against a 0-length name, but not a 0-length domain name; which results in an empty array being passed as an argument.  Possible fix would be to ensure at least one character is defined.  

Alternately, it seems the original length check is unnecessary if the arrays are large enough, which would be 255 for domain and 256 for user (+1 for null).

**Comment by mfujitaitrs** [comment]
Hi @dbwiddis, I'll try to use the latest snapshot on my test and get back with the results.

**Comment by mfujitaitrs** [comment]
Hi @dbwiddis  this is the debug log from my latest run:

>  WARN  oshi.software.os.windows.WindowsOSProcess - Failed LookupAccountSid: Sid=WinNT$PSID$ByReference(native@0x20637423740) (8 bytes) {
>   Pointer sid@0x0=null
> }, cchName=14, cchDomainName=16. Trying again.
>  WARN  oshi.software.os.windows.WindowsOSProcess - Trying LookupAccountSid: Sid=WinNT$PSID$ByReference(native@0x20637423740) (8 bytes) {
>   Pointer sid@0x0=null
> }, cchName=14, cchDomainName=16.
>  WARN  oshi.software.os.windows.WindowsOSProcess - Failed LookupAccountSid: Sid=WinNT$PSID$ByReference(native@0x20637423740) (8 bytes) {
>   Pointer sid@0x0=null
> }, cchName=14, cchDomainName=16. Bailing out.
>  WARN  oshi.software.os.windows.WindowsOSProcess - Failed to query user info for process 3148 (rdpclip): The parameter is incorrect.
>  WARN  oshi.software.os.windows.WindowsOSProcess - Failed LookupAccountSid: Sid=WinNT$PSID$ByReference(native@0x206372241b0) (8 bytes) {
>   Pointer sid@0x0=native@0x4e659f66b7987bf8
> }, cchName=7, cchDomainName=13. Trying again.
>  WARN  oshi.software.os.windows.WindowsOSProcess - Trying LookupAccountSid: Sid=WinNT$PSID$ByReference(native@0x206372241b0) (8 bytes) {
>   Pointer sid@0x0=native@0x6f006f006c0079
> }, cchName=7, cchDomainName=13.
>  WARN  oshi.software.os.windows.WindowsOSProcess - Failed LookupAccountSid: Sid=WinNT$PSID$ByReference(native@0x206372241b0) (8 bytes) {
>   Pointer sid@0x0=native@0x6f006f006c0079
> }, cchName=7, cchDomainName=13. Bailing out.
>  WARN  oshi.software.os.windows.WindowsOSProcess - Failed to query user info for process 1904 (LiteAgent): The parameter is incorrect.

This is the process for PID 1904:
![image](https://user-images.githubusercontent.com/42991925/110645762-3880d200-81f1-11eb-950e-b2b69994d9cb.png)

**Comment by dbwiddis** [comment]
Well, that at least rules out issues with the name and domain name. The first one is apparently "Administrator" (13 letters plus null) and the second one "SYSTEM" (6 letters plus null).  The SID pointer is inconsistent, on the first one it's null and on the second one the pointer value changes.  

I'm thinking along the lines of we don't own the memory at the address or something, but not sure yet.  Continuing to look into this.

**Comment by dbwiddis** [comment]
I think I've identified the problem. Discussing this further [on this thread](https://groups.google.com/g/jna-users/c/RAJ-MBcvOuI).

**Comment by dbwiddis** [comment]
I've fixed this in ed77b532c79a19ad2c1a21c1ea7060f069c0362f which should be in SNAPSHOT right now.  @mfujitaitrs or @rnaval can you please re-test and see if this resolves the issue?  If so I'll submit it upstream to JNA.

Also, the "pointer" 0x6f006f006c0079 is clearly text "ooly".  Curious if that has any relation to a portion of a name of any of your users or domains which would confirm my "losing memory allocation" diagnosis.

**Comment by mfujitaitrs** [comment]
Hi @dbwiddis, I wasn't able to reproduce the issue for around 3 hours using the latest snapshot :)  
I also re-ran an old build to ensure that the issue is still reproducible on my environment.

**Comment by dbwiddis** [comment]
OK great!  The root cause was fixed more broadly in https://github.com/java-native-access/jna/pull/1326 which will be in JNA 5.8.0 soon.  I'll go ahead and close this!
