### ISSUE TITLE
Unresolved dependency in OSGi container on Linux

### ISSUE THREAD

**Issue by mmopenet** [oshi/oshi#752]
I am trying to run oshi-core 3.12.1 in Felix OSGi container.
I can see both com.sun.jna and com.sun.jna.platform bundles version 5.1.0 are active.
However osgi-core bundle is missing mandatory dependency on com.sun.jna.platform.linux package, but
the com.sun.jna.platform bundle does not export this package.

**Comment by mmopenet** [comment]
Well, fixing it in JNA project will not change dependency version specified in oshi-core. The pom will need to be updated.
I have logged JNA issue https://github.com/java-native-access/jna/issues/1054

**Comment by dbwiddis** [comment]
We keep OSHI pointing to the latest JNA, which is currently 5.2.0 in SNAPSHOT. I assume this will be fixed in the JNA 5.3.0 release which we'll update to when it comes out.

**Comment by mmopenet** [comment]
OK. Thanks.

**Comment by dbwiddis** [comment]
I submitted a PR on JNA which has been merged, so now we just have to wait for the next version bump.

**Comment by dbwiddis** [comment]
JNA 5.3.0 fixes this, and I've just released OSHI 3.13.1 that depends on the new version.  Resolving this.

**Comment by dougreed** [comment]
It still failed in the same way.  Maybe I need to add some include file?  There is no error in the build.  I am most happy to help troubleshoot this if I can be of assistance, but I don’t know what to do.  It works on OSX, but fails on Linux.

Distributor ID:	LinuxMint
Description:	Linux Mint 18.2 Sonya
Release:	18.2
Codename:	sonya
Linux cp-master 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


            <dependency>
                <groupId>com.github.oshi</groupId>
                <artifactId>oshi-core</artifactId>
                <version>3.13.1</version>
            </dependency>
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna</artifactId>
                <version>5.3.0</version>
            </dependency>


Exception in thread "SystemAnalyzer" java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;)Lcom/sun/jna/Library;
	at com.sun.jna.platform.linux.LibC.<clinit>(LibC.java:43)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:43)
	at sun.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:156)
	at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1088)
	at java.lang.reflect.Field.getFieldAccessor(Field.java:1069)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.sun.jna.Native.loadLibraryInstance(Native.java:591)
	at com.sun.jna.Native.getLibraryOptions(Native.java:666)
	at com.sun.jna.Native.getStructureAlignment(Native.java:760)
	at com.sun.jna.Structure.setAlignType(Structure.java:269)
	at com.sun.jna.Structure.<init>(Structure.java:186)
	at com.sun.jna.Structure.<init>(Structure.java:182)
	at com.sun.jna.Structure.<init>(Structure.java:169)
	at com.sun.jna.Structure.<init>(Structure.java:161)
	at com.sun.jna.platform.linux.LibC$Sysinfo.<init>(LibC.java:47)
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<init>(LinuxGlobalMemory.java:62)
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.getMemory(LinuxHardwareAbstractionLayer.java:59)
	at cpssd.tools.SelfDiscover.getApplicationInstance(SelfDiscover.java:426)
	at cpssd.SystemAnalyzer.<clinit>(SystemAnalyzer.java:83)

**Comment by dbwiddis** [comment]
Try also including `jna-platform` version 5.3.0

**Comment by dougreed** [comment]
It made no difference. … Sorry.



Douglas Reed
r.douglas.reed@gmail.com

**Comment by dbwiddis** [comment]
Are you using the OSGi bundle to include dependencies?  Are the dependencies at the top level of your POM?

**Comment by dougreed** [comment]
Daniel,


            <dependency>
                <groupId>com.github.oshi</groupId>
                <artifactId>oshi-core</artifactId>
                <version>3.5.0</version>
            </dependency>
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna</artifactId>
                <version>5.3.0</version>
            </dependency>
            <dependency>
                <groupId>net.java.dev.jna</groupId>
                <artifactId>jna-platform</artifactId>
                <version>5.3.0</version>
            </dependency>

In the root pom, and in the underlying project pom (minus the version line).

I am not aware of an oshi “bundle”?  I just checked maven, and there is an ‘oshi-core’, ‘oshi-parent’, ‘oshi-dist’, ‘oshi-json’, and 'oshi-core-shaded’.  I have always used ‘oshi-core’.  Am I using the wrong library?



Douglas Reed
r.douglas.reed@gmail.com

**Comment by dbwiddis** [comment]
Hey Douglas.  Sorry for any confusion.  You replied to a pre-existing ticket regarding an OSGi container, which was the bug recently fixed.  It is totally fine to include just `oshi-core` in your POM (and it should include the correct JNA dependencies if it's listed first).

Earlier you indicated OSHI 3.13.1 in your POM but in the latest copy you show 3.5.0.

You do indicate that you are not including the version in your underlying project.  That may be a problem if you're not referencing the parent version in any other way.  Please try including the version number (or referencing the parent pom version number.  See [this post](https://stackoverflow.com/questions/10582054/maven-project-version-inheritance-do-i-have-to-specify-the-parent-version).

**Comment by dougreed** [comment]
Daniel,

Oops.  Yes, the POM I sent shows what it looks like currently.  I had 3.13.1 in the POM, but I backed it off because it didn’t work.  I will try putting the Version in the child.  I doubt that will fix it as I don’t have the version in any of the sub-projects.  they get the version from the parent.  I will try adding it and let you know.


Douglas Reed
r.douglas.reed@gmail.com
